= Draft FreeBSD Git docs

:doctype: article
:description: A first draft of FreeBSD Git docs
:author: Warner Losh
:email: imp@FreeBSD.org
:source-highlighter: rouge
:rouge-style: github
:icons: font
:toc: preamble


This repo contains the draft docs for the FreeBSD migration to Git.

== How to read the docs

Please check out the link:SUMMARY.adoc[SUMMARY] page for a clean and complete list of the documentation.

The best place to start is with the link:mini-primer.md[FreeBSD mini-git Primer] if
you are coming to this fresh. Otherwise the best place to start is the
link:src-cvt.md[FreeBSD Src Committer Transition Guide] if you have an existing source tree
from the project you'd like to convert over to the new git repo. Once you've
read that, you can read the link:mini-primer.md[FreeBSD mini-git Primer] for a
general primer.

More advanced topics can be found in the link:faq.md[Git FAQ].

Other files contain information about different aspects of the src or doc repository that FreeBSD developers with commit access need to know.

== Contributing

Please feel free to submit pull requests for typos, clearer language, additional
topics, etc.

Please open issues for something that you're just noting the problem, but
don't have a solution for.
